version: '2'
services:
  mongo:
    image: mongo:3.2.9
    volumes:
      - "/var/abx/mongodb:/data/db"
    ports:
      - "27017:27017"

  redis:
    image: redis:3.2.3
    ports:
        - "6379:6379"

  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: autobox-dev-db
    volumes:
      - "/var/abx/postgres-dev:/var/lib/postgresql/data"

  rabbit:
    image: byteflair/rabbitmq-stomp
    ports:
        - "15672:15672"
        - "5672:5672"
        - "15674:15674"
        - "61613:61613"
    environment:
        RABBITMQ_ERLANG_COOKIE: abx-01
        RABBITMQ_DEFAULT_USER: abx-admin
        RABBITMQ_DEFAULT_PASS: abx01

  autobox-auth:
    image: quay.io/abxbo/autobox-auth:latest.dev
    ports:
      - "3380"
    entrypoint: ../wait-for-it.sh postgres:5432 -- npm start
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongo/autobox-dev-db
      POSTGRES_HOST: postgres
      POSTGRES_DB: autobox-dev-db
    links:
      - mongo
      - postgres

  autobox-api:
    image: quay.io/abxbo/autobox-api:latest.dev
    volumes:
      - /var/abx/log-dev/api:/var/log/abx/api
    ports:
      - "9999:8080"
    entrypoint: ../wait-for-it.sh rabbit:5672 -- npm start
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongo/autobox-dev-db
      POSTGRES_HOST: postgres
      POSTGRES_DB: autobox-dev-db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AUTH_SERVER_URL: http://autobox-auth:3380
      CORS_WHITE_LIST: http://www.dev-autoboxcorp.com:8080, http://www.dev-autoboxcorp.com, http://dev-autoboxcorp.com, http://www.dev-autoboxcorp.com:8081, http://www.dev-autoboxcorp.com:7000, http://dev-autoboxcorp.com:7000, http://www.dev-autoboxcorp.com:8880, http://dev-autoboxcorp.com:8880
      RABBITMQ_HOST: rabbit
      RABBITMQ_USER: abx-admin
      RABBITMQ_PASSWORD: abx01
    links:
      - rabbit
      - mongo
      - postgres
      - redis
      - autobox-auth

